//
//  File.swift
//  
//
//  Created by Matt Bonney on 7/14/22.
//

import SwiftUI
public extension LabeledColor {
    struct watchOS {
        static let yellowGold = LabeledColor("yellow gold", hex: "#edda98")
        static let gold = LabeledColor("gold", hex: "#cead7a")
        static let roseGold = LabeledColor("rose gold", hex: "#f2c1a2")
        static let white = LabeledColor("white", hex: "#ffffff")
        static let gray = LabeledColor("gray", hex: "#8e8d93")
        static let red = LabeledColor("red", hex: "#df0b24")
        static let orange = LabeledColor("orange", hex: "#fe5131")
        static let nectarine = LabeledColor("nectarine", hex: "#fc694f")
        static let apricot = LabeledColor("apricot", hex: "#fc7351")
        static let peach = LabeledColor("peach", hex: "#e57e5e")
        static let papaya = LabeledColor("papaya", hex: "#ff8542")
        static let lightOrange = LabeledColor("light orange", hex: "#ff9602")
        static let mellowYellow = LabeledColor("mellow yellow", hex: "#f6f3bd")
        static let yellow = LabeledColor("yellow", hex: "#e9cb0d")
        static let pollen = LabeledColor("pollen", hex: "#ffd25b")
        static let canaryYellow = LabeledColor("canary yellow", hex: "#fedd44")
        static let flashLight = LabeledColor("flash light", hex: "#f7ec00")
        static let flash = LabeledColor("flash", hex: "#e1f323")
        static let green = LabeledColor("green", hex: "#8ce229")
        static let spearmint = LabeledColor("spearmint", hex: "#84e98c")
        static let mint = LabeledColor("mint", hex: "#adec9d")
        static let turquoise = LabeledColor("turquoise", hex: "#9ed5cb")
        static let lightBlue = LabeledColor("light blue", hex: "#6ac4dc")
        static let blue = LabeledColor("blue", hex: "#19b6fb")
        static let royalBlue = LabeledColor("royal blue", hex: "#62aded")
        static let cerulean = LabeledColor("cerulean", hex: "#95c4e8")
        static let lilac = LabeledColor("lilac", hex: "#c1d8fc")
        static let mistBlue = LabeledColor("mist blue", hex: "#b3b8a7")
        static let azure = LabeledColor("azure", hex: "#879aa1")
        static let stormGray = LabeledColor("storm gray", hex: "#689797")
        static let pacificGreen = LabeledColor("pacific green", hex: "#127f9c")
        static let blueCobalt = LabeledColor("blue cobalt", hex: "#477f9d")
        static let darkTeal = LabeledColor("dark teal", hex: "#357293")
        static let blueHorizon = LabeledColor("blue horizon", hex: "#26689d")
        static let denimBlue = LabeledColor("denim blue", hex: "#5b83a8")
        static let midnightBlue = LabeledColor("midnight blue", hex: "#6083be")
        static let oceanBlue = LabeledColor("ocean blue", hex: "#7288c7")
        static let delftBlue = LabeledColor("delft blue", hex: "#5677bf")
        static let indigo = LabeledColor("indigo", hex: "#5864a2")
        static let purple = LabeledColor("purple", hex: "#987cf7")
        static let ultraViolet = LabeledColor("ultra violet", hex: "#7157be")
        static let lavenderGray = LabeledColor("lavender gray", hex: "#8687a4")
        static let lavender = LabeledColor("lavender", hex: "#b399a6")
        static let pinkSand = LabeledColor("pink sand", hex: "#f4c1bd")
        static let lightPink = LabeledColor("light pink", hex: "#f4b0aa")
        static let vintageRose = LabeledColor("vintage rose", hex: "#f4aba5")
        static let pink = LabeledColor("pink", hex: "#fe5964")
        static let electricPink = LabeledColor("electric pink", hex: "#ff4e51")
        static let dragonFruit = LabeledColor("dragon fruit", hex: "#f34a7e")
        static let hibiscus = LabeledColor("hibiscus", hex: "#fa255b")
        static let roseRed = LabeledColor("rose red", hex: "#b92946")
        static let camellia = LabeledColor("camellia", hex: "#c94544")
        static let flamingo = LabeledColor("flamingo", hex: "#d3836a")
        static let walnut = LabeledColor("walnut", hex: "#b08662")
        static let stone = LabeledColor("stone", hex: "#ae9980")
        static let antiqueWhite = LabeledColor("antique white", hex: "#d4b694")
        static let softWhite = LabeledColor("soft white", hex: "#ddd1bb")
        static let pebble = LabeledColor("pebble", hex: "#ad9d8e")
        static let cocoa = LabeledColor("cocoa", hex: "#9b8d8c")
        static let darkOlive = LabeledColor("dark olive", hex: "#8c8c76")
        static let voltNike = LabeledColor("volt", hex: "#dffd04")
        static let celestialTealNike = LabeledColor("celestial teal", hex: "#4c7b7c")
        static let smokyMauveNike = LabeledColor("smoky mauve", hex: "#ab7e6b")
        static let oliveFlakNike = LabeledColor("olive flak", hex: "#7d713a")
        static let cargoKhakiNike = LabeledColor("cargo khaki", hex: "#4e4e32")
        static let obsidianIndigoNike = LabeledColor("obsidian indigo", hex: "#2d2b36")
        static let anthraciteNike = LabeledColor("anthracite", hex: "#686969")
        static let wolfGrayNike = LabeledColor("wolf gray", hex: "#a6a5aa")
        static let lightSilverNike = LabeledColor("light silver", hex: "#c4c5c0")
        static let particleBeigeNike = LabeledColor("particle beige", hex: "#c4b1a4")
        static let lightBoneNike = LabeledColor("light bone", hex: "#c9bc9a")
        static let terraBlushNike = LabeledColor("terra blush", hex: "#a67762")
        static let totalOrangeNike = LabeledColor("total orange", hex: "#ee664d")
        static let brightCrimsonNike = LabeledColor("bright crimson", hex: "#ff3838")
        static let barelyRoseNike = LabeledColor("barely rose", hex: "#f9cebd")
        static let lightVioletNike = LabeledColor("light violet", hex: "#ffcfba")
        static let violetDustNike = LabeledColor("violet dust", hex: "#ad757f")
        static let indigoNike = LabeledColor("indigo", hex: "#587ba1")
        static let blueOrbitNike = LabeledColor("blue orbit", hex: "#0189a1")
        static let auroraGreenNike = LabeledColor("aurora green", hex: "#92dbd8")
        static let tealTintNike = LabeledColor("teal tint", hex: "#d7f5d0")
        static let hyperGrapeNike = LabeledColor("hyper grape", hex: "#8549b3")
        static let spruceFogNike = LabeledColor("spruce fog", hex: "#c6bd93")
    }
}
